### ISSUE TITLE
pdftotext and tiktoken

### ISSUE THREAD

**Issue by andreifoldes** [raghavan/PdfGptIndexer#1]
Hi, wanted to try out this repo, but got the following error when running the indexer after following instructions.

I think in addition to the libraries listed I needed to:
conda install pdftotext and tiktoken

````
(pdfgptindexer) C:\Users\xxx\Git\PdfGptIndexer>python pdf_gpt_indexer.py
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
  File "C:\Users\xxx\Anaconda3\envs\pdfgptindexer\Lib\site-packages\textract\parsers\utils.py", line 87, in run
    pipe = subprocess.Popen(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Anaconda3\envs\pdfgptindexer\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\xxx\Anaconda3\envs\pdfgptindexer\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxx\Git\PdfGptIndexer\pdf_gpt_indexer.py", line 62, in <module>
    all_chunks = process_pdf_folder("./pdf", "./text");
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Git\PdfGptIndexer\pdf_gpt_indexer.py", line 35, in process_pdf_folder
    doc = textract.process(filepath)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Anaconda3\envs\pdfgptindexer\Lib\site-packages\textract\parsers\__init__.py", line 79, in process
    return parser.process(filename, input_encoding, output_encoding, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Anaconda3\envs\pdfgptindexer\Lib\site-packages\textract\parsers\utils.py", line 46, in process
    byte_string = self.extract(filename, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Anaconda3\envs\pdfgptindexer\Lib\site-packages\textract\parsers\pdf_parser.py", line 29, in extract
    raise ex
  File "C:\Users\xxx\Anaconda3\envs\pdfgptindexer\Lib\site-packages\textract\parsers\pdf_parser.py", line 21, in extract
    return self.extract_pdftotext(filename, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Anaconda3\envs\pdfgptindexer\Lib\site-packages\textract\parsers\pdf_parser.py", line 44, in extract_pdftotext
    stdout, _ = self.run(args)
                ^^^^^^^^^^^^^^
  File "C:\Users\xxx\Anaconda3\envs\pdfgptindexer\Lib\site-packages\textract\parsers\utils.py", line 95, in run
    raise exceptions.ShellError(
textract.exceptions.ShellError: The command `pdftotext ./pdf\sample.pdf -` failed with exit code 127
------------- stdout -------------
------------- stderr -------------
```

python --version
Python 3.11.4

**Comment by manfromdownunder** [comment]
create a file called requirements.txt that contains:

aiohttp==3.8.4
aiosignal==1.3.1
argcomplete==1.10.3
async-timeout==4.0.2
attrs==23.1.0
beautifulsoup4==4.8.2
certifi==2023.5.7
chardet==3.0.4
charset-normalizer==3.2.0
compressed-rtf==1.0.6
dataclasses-json==0.5.9
docx2txt==0.8
ebcdic==1.1.1
extract-msg==0.28.7
faiss-cpu==1.7.4
filelock==3.12.2
frozenlist==1.3.3
fsspec==2023.6.0
greenlet==2.0.2
huggingface-hub==0.16.4
idna==3.4
IMAPClient==2.1.0
langchain==0.0.228
langchainplus-sdk==0.0.20
lxml==4.9.3
Markdown==3.4.3
marshmallow==3.19.0
marshmallow-enum==1.5.1
multidict==6.0.4
mypy-extensions==1.0.0
numexpr==2.8.4
numpy==1.25.1
olefile==0.46
openai==0.27.8
openapi-schema-pydantic==1.2.4
packaging==23.1
pdfminer.six==20191110
Pillow==10.0.0
pycryptodome==3.18.0
pydantic==1.10.11
python-pptx==0.6.21
PyYAML==6.0
regex==2023.6.3
requests==2.31.0
safetensors==0.3.1
six==1.12.0
sortedcontainers==2.4.0
soupsieve==2.4.1
SpeechRecognition==3.8.1
SQLAlchemy==2.0.18
tenacity==8.2.2
textract==1.6.5
tiktoken==0.4.0
tokenizers==0.13.3
tqdm==4.65.0
transformers==4.30.2
typing-inspect==0.9.0
typing_extensions==4.7.1
tzlocal==5.0.1
urllib3==2.0.3
xlrd==1.2.0
XlsxWriter==3.1.2
yarl==1.9.2

run pip3 install -r requirements.txt

credits go to https://github.com/gszr/wikigpt

**Comment by raghavan** [comment]
I think installing pypdf should resolve the pdftotext dependency issue, and yes, tiktoken is a dependency for the tokenizer. I have updated the readme file. Having a requirements.txt is a good idea, will look into it. Thanks for your suggestions.
